Add in a gpu node soft anti-affinity for pods that don't request GPUs
red-hat-data-services/jupyterhub-singleuser-profiles pull request #61
Opened 2022-05-31 20:51 UTC by Xaenalt

This commit adds in a soft anti-affinity for nodes tagged as GPU
nodes by the Nvidia GPU operator. When creating a pod that doesn't
request any GPUs, it will have an affinity added that avoids GPU
tagged nodes if possible. If there are no available nodes that
satisfy that requirement, it will allow scheduling onto the GPU
nodes to avoid a scheduling failure.

To test, apply this fix and then observe the resulting pod spec for GPU and non-GPU pods. Non-GPU pods should have:
```
        'preferredDuringSchedulingIgnoredDuringExecution': [{
          'preference': {'matchExpressions': [{
            'key': 'nvidia.com/gpu.present', 'operator': 'NotIn', 'values': ['true']}]},
          'weight': 1}]
```

See also https://github.com/opendatahub-io/jupyterhub-odh/pull/135 and https://github.com/opendatahub-io/odh-manifests/pull/556 for previous attempts at this feature

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-3074
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

2022-05-31 20:52 UTC, Xaenalt commented
@crobby @LaVLaS @anishasthana PTAL

Also, any idea how we'd test this? xD

2022-06-02 16:15 UTC, Xaenalt commented on jupyterhub_singleuser_profiles/profiles.py
> +        self.apply_pod_schedulers(node_tolerations, node_affinity, pod)
@LaVLaS something like this?

2022-06-07 13:31 UTC, Xaenalt commented
For the CM, will need something like:
```
    cpuTypes:
      cpuOne:
        preferredDuringSchedulingIgnoredDuringExecution:
          preference:
            matchExpressions:
              - key: 'nvidia.com/gpu.present'
                operator: 'NotIn'
                values:
                  - true
                weight: 1
```

2022-06-15 17:53 UTC, LaVLaS requested changes
@Xaenalt This is a great feature that we want to include in upstream ODH. Please create a PR in  https://github.com/opendatahub-io/jupyterhub-singleuser-profiles

2022-06-15 17:53 UTC, LaVLaS commented on jupyterhub_singleuser_profiles/profiles.py
> +    cpu_types = config_map_yaml.get("cpuTypes", {})
`config_map_yaml` is not defined in this function or global so this will not work. Similar to the `apply_gpu_config` function, you will need to request `cpu_types` as a function argument.

2022-06-15 17:53 UTC, LaVLaS commented on jupyterhub_singleuser_profiles/profiles.py
> +    if (int(gpu_count) == 0) or ('nvidia.com/gpus' not in notebook_container.resources.requests):
For consistency and error proofing, you need to reference the static var `_GPU_KEY` for the resource label that is already defined for `nvidia.com/gpu`.

The check for the `nvidia.com/gpu` pod resource will probably always return `False` since the resource will not be applied until after `apply_gpu_config` is run against the `pod` object

2022-06-15 17:53 UTC, LaVLaS commented on jupyterhub_singleuser_profiles/profiles.py
> +  def apply_cpu_config(self, profile, pod):
Since this is has the `@classmethod` propery, you will need to use function arguments to access any runtime information

2022-06-15 20:31 UTC, closed without merging

2022-06-15 20:41 UTC, Xaenalt commented
Superseded by https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/pull/222